name: "Test Stale Action (ESM + ESLint Migration)"

on:
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write
  actions: write

jobs:
  test-stale:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Stale Action
        uses: chiranjib-swain/stale@test-nodefetch
        with:
          days-before-stale: 150
          days-before-close: 50
