
name: Stale
on:
  # schedule:
  #   - cron: '40 3,4,5,6,7 * * *'
  workflow_dispatch: {} # Allow also to run manually, for easier testing

jobs:
  stale:
    permissions:
      actions: write
      contents: write # for delete-branch option
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: chiranjib-swain/stale@force-state-reason-pr
      with:
        operations-per-run: 150
        days-before-stale: 173
        days-before-pr-close: 0
        ascending: true  # Start from processing oldest PRs first.
        stale-issue-message: '...'
        close-issue-message: '...'
        stale-pr-message: '...'
        close-pr-message: '...'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        exempt-issue-labels: 'no-stale'
        exempt-pr-labels: 'no-stale'

        remove-stale-when-updated: false  # Important: set to false
        delete-branch: false              # Disable for safety during testing
        enable-statistics: true
