name: 'Stale PRs only'

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual triggering
permissions:
  issues: write
  pull-requests: write
  actions: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: "This PR hasn't received any updates in a year and will be automatically closed in 30 days. Feel free to re-open it if you plan to continue working on that pull request or think it deserves attention from Flathub admins"Add commentMore actions
          days-before-stale: -1
          days-before-close: -1
          days-before-pr-stale: 365
          days-before-pr-close: 30
          only-pr-labels: awaiting-changes,blocked,work-in-progress,awaiting-upstream
          remove-pr-stale-when-updated: true