name: "Sort issues and PRs"
on:
  workflow_dispatch:
permissions:
  issues: write
  pull-requests: write
  actions: write
  
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: suyashgaonkar/stale@sort_issues_by
        with:
          sort-by: "updated"
          # Add other options as needed for your test (see stale docs)
