name: 'Mark stale issues and pull requests'

on:
  workflow_dispatch: # Allows manual triggering
permissions:
  issues: write
  pull-requests: write
  actions: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: chiranjib-swain/stale@feature/rate-limit-retry
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is stale because it has been open for 30 days with no activity.'
          stale-pr-message: 'This pull request is stale because it has been open for 30 days with no activity.'
          days-before-issue-stale: 15
          days-before-pr-stale: 20
          days-before-close: 7
          remove-stale-when-updated: 'true'
